web/router.ex
defmodule HelloPhoenix.Router do
  use HelloPhoenix.Web, :router
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelloPhoenix do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/rules", PageController, :rules
    get "/apps", PageController, :apps
    get "/admin", PageController, :admin

    resources "/activities", ActivityController
    resources "/users", UserController
    resources "/events", EventController
    resources "/teams", TeamController
    resources "/logs", LogController
    get       "/summary", SummaryController, :index
    get       "/summary/totals", SummaryController, :totals
    get       "/summary/teams", SummaryController, :teams
    get       "/summary/csv", SummaryController, :csv
    get       "/summary/combined", SummaryController, :combined


    get    "/register", RegistrationController, :new
    post   "/register", RegistrationController, :create

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
    get    "/reset_password",  SessionController, :reset
    post    "/reset",  SessionController, :reset_pass
    get    "/request_reset",  SessionController, :request_reset
    post    "/request_reset",  SessionController, :request_reset_send

  end

  #Other scopes may use custom stacks.
  scope "/api", HelloPhoenix do
    pipe_through :api
    scope "/v1", V1, as: :v1 do
      resources "/teams", TeamController
      resources "/activities", ActivityController
      resources "/logs", LogController
      get       "/login",  SessionController, :create
      post      "/register", RegistrationController, :create
      get       "/event", EventController, :index
      get       "/summary", SummaryController, :index
    end
  end
end

web/views/layout_view.ex
defmodule HelloPhoenix.LayoutView do
  use HelloPhoenix.Web, :view

  def admin?(conn) do
    HelloPhoenix.Session.current_user(conn).admin == true
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Fitness Challenge</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
mixpanel.init("f4713a69c0f4c6c93d9545ea966e86b0");</script><!-- end Mixpanel -->
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ul class="nav nav-pills pull-right">
            <li><span><a href="/" class="btn btn-info">Home</a></span></li>
            <li><span><a href="/rules" class="btn btn-info">Rules</a></span></li>

          <%= if logged_in?(@conn) do %>
            <li><script type="text/javascript">
              mixpanel.identify("<%= current_user(@conn).email %>");
              mixpanel.people.set({
                  'name': '<%= current_user(@conn).name %>'
              });
            </script></li>
            <li><span><a href="/logs/new" class="btn btn-info">Log an Activity</a></span></li>
            <%= if admin?(@conn) do %>
              <li><span><a href="/admin" class="btn btn-warning">Admin</a></span></li>
            <%= end %>
            <li><span style="padding: 6px 12px; display: inline-block;"><%= current_user(@conn).name %></span></li>
            <li><%= link "Logout", to: session_path(@conn, :delete), method: :delete, class: "btn btn-primary" %></li>
          <% else %>
            <li><span><%= link "Login",    to: session_path(@conn, :new), class: "btn btn-primary" %></span></li>
            <!-- <li><span><%= link "Register", to: registration_path(@conn, :new), class: "btn btn-primary" %></span></li> -->
          <% end %>
        </ul>
        <br><br><br>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script type="text/javascript">
    mixpanel.track_links(".nav a", "click nav link", {
        "referrer": document.referrer
    });
    </script>
  </body>
</html>