web/router.ex
defmodule HelloPhoenix.Router do
  use HelloPhoenix.Web, :router
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelloPhoenix do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/rules", PageController, :rules
    get "/apps", PageController, :apps
    get "/admin", PageController, :admin

    resources "/activities", ActivityController
    resources "/users", UserController
    resources "/events", EventController
    resources "/teams", TeamController
    resources "/logs", LogController
    get       "/summary", SummaryController, :index
    get       "/summary/totals", SummaryController, :totals
    get       "/summary/teams", SummaryController, :teams
    get       "/summary/csv", SummaryController, :csv
    get       "/summary/combined", SummaryController, :combined


    get    "/register", RegistrationController, :new
    post   "/register", RegistrationController, :create

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
    get    "/reset_password",  SessionController, :reset
    post    "/reset",  SessionController, :reset_pass
    get    "/request_reset",  SessionController, :request_reset
    post    "/request_reset",  SessionController, :request_reset_send

  end

  #Other scopes may use custom stacks.
  scope "/api", HelloPhoenix do
    pipe_through :api
    scope "/v1", V1, as: :v1 do
      resources "/teams", TeamController
      resources "/activities", ActivityController
      resources "/logs", LogController
      get       "/login",  SessionController, :create
      post      "/register", RegistrationController, :create
      get       "/event", EventController, :index
      get       "/summary", SummaryController, :index
    end
  end
end

web/models/team.ex
defmodule HelloPhoenix.Team do
  use HelloPhoenix.Web, :model

  schema "teams" do
    field :name, :string
    belongs_to :event, HelloPhoenix.Event
    belongs_to :captain, HelloPhoenix.User
    has_many :users, HelloPhoenix.User

    timestamps
  end

  @required_fields ~w(name)
  @optional_fields ~w(captain_id)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end

  def total_points(team) do
    users = Enum.reduce(team.users, 0, fn(users, count) ->
      count = Enum.reduce(users.logs, 0, &(HelloPhoenix.Log.points(&1) + &2))
    end)
  end
end

web/controllers/team_controller.ex
defmodule HelloPhoenix.TeamController do
  use HelloPhoenix.Web, :controller

  alias HelloPhoenix.Team
  alias HelloPhoenix.User
  plug HelloPhoenix.Plugs.AdminProtection

  plug :scrub_params, "team" when action in [:create, :update]

  def index(conn, _params) do
    teams = Repo.all(Team)
    render(conn, "index.html", teams: teams)
  end

  def new(conn, _params) do
    changeset = Team.changeset(%Team{} |> Repo.preload ([:captain]))
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"team" => team_params}) do
    changeset = Team.changeset(%Team{}, team_params)

    case Repo.insert(changeset) do
      {:ok, _team} ->
        conn
        |> put_flash(:info, "Team created successfully.")
        |> redirect(to: team_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    team = Repo.get!(Team, id) |> Repo.preload ([:captain, :users])
    render(conn, "show.html", team: team)
  end

  def edit(conn, %{"id" => id}) do
    team = Repo.get!(Team, id) |> Repo.preload ([:captain, :users])
    changeset = Team.changeset(team)
    render(conn, "edit.html", team: team, changeset: changeset, captains: captains)
  end

  def update(conn, %{"id" => id, "team" => team_params}) do
    team = Repo.get!(Team, id) |> Repo.preload ([:captain])
    changeset = Team.changeset(team, team_params)

    case Repo.update(changeset) do
      {:ok, team} ->
        conn
        |> put_flash(:info, "Team updated successfully.")
        |> redirect(to: team_path(conn, :show, team))
      {:error, changeset} ->
        render(conn, "edit.html", team: team, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    team = Repo.get!(Team, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(team)

    conn
    |> put_flash(:info, "Team deleted successfully.")
    |> redirect(to: team_path(conn, :index))
  end


  def captains do
    # Add query to only find Captains (preference?)
    captains = Repo.all(User)
      |> Enum.map( fn(captain) ->
      { captain.name, captain.id}
    end)
  end

end

web/controllers/v1/team_controller.ex
defmodule HelloPhoenix.V1.TeamController do
  use HelloPhoenix.Web, :controller

  alias HelloPhoenix.Team

  plug HelloPhoenix.Plugs.Authenticated

  plug :scrub_params, "team" when action in [:create, :update]

  def index(conn, _params) do
    teams = Repo.all(Team)
    render(conn, "index.json", teams: teams)
  end

  def show(conn, %{"id" => id}) do
    team = Repo.get!(Team, id)
    render conn, "show.json", team: team
  end

end

web/views/team_view.ex
defmodule HelloPhoenix.TeamView do
  use HelloPhoenix.Web, :view
end

web/views/v1/team_view.ex
defmodule HelloPhoenix.V1.TeamView do
  use HelloPhoenix.Web, :view

  def render("index.json", %{teams: teams}) do
    %{data: render_many(teams, HelloPhoenix.V1.TeamView, "team.json")}
  end

  def render("show.json", %{team: team}) do
    %{data: render_one(team, HelloPhoenix.V1.TeamView, "team.json")}
  end

  def render("team.json", %{team: team}) do
    %{
      id: team.id,
      title: team.name
    }
  end

end

web/templates/team/edit.html.eex
<h2>Edit team</h2>

<%= render "form.html", changeset: @changeset,
                        action: team_path(@conn, :update, @team), captains: @captains %>

<%= link "Back", to: team_path(@conn, :index) %>

web/templates/team/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, "Name", class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :captain, "Captain", class: "control-label" %>
    <%= select f, :captain_id, @captains, prompt: "Choose a captain"%>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/team/index.html.eex
<h2>Listing teams</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Event</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for team <- @teams do %>
    <tr>
      <td><%= team.name %></td>
      <td><%= team.event_id %></td>

      <td class="text-right">
        <%= link "Show", to: team_path(@conn, :show, team), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: team_path(@conn, :edit, team), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: team_path(@conn, :delete, team), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New team", to: team_path(@conn, :new) %>

web/templates/team/new.html.eex
<h2>New team</h2>

<%= render "form.html", changeset: @changeset,
                        action: team_path(@conn, :create) %>

<%= link "Back", to: team_path(@conn, :index) %>

web/templates/team/show.html.eex
<h2>Show team</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @team.name %>
  </li>

  <li>
    <strong>Event:</strong>
    <%= @team.event_id %>
  </li>

  <li>
    <strong>Captain:</strong>
    <%= link @team.captain.name, to: user_path(@conn, :show, @team.captain) %>
  </li>

  <li>
    <strong>Team Members:</strong>
    <ul>
    <%= for user <- @team.users do %>
      <li><%= link user.name, to: user_path(@conn, :show, user) %></li>
    <% end %>
    </ul>
  </li>

</ul>

<%= link "Edit", to: team_path(@conn, :edit, @team) %>
<%= link "Back", to: team_path(@conn, :index) %>